/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minor_project;



import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Image;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.Font;

/**
 *
 * @author Himanshu Singare
 */
public class CREATE extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs=null;
    String filename=null;
   
    /**
     * Creates new form CREATE
     */
    public CREATE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        phn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        objective = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        professional = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        educational = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        achievement_1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        achievement_2 = new javax.swing.JTextField();
        achievement_3 = new javax.swing.JTextField();
        skill_1 = new javax.swing.JTextField();
        skill_2 = new javax.swing.JTextField();
        skill_3 = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        fathername = new javax.swing.JTextField();
        language = new javax.swing.JTextField();
        nationality = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        place = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        strength_1 = new javax.swing.JTextField();
        strength_2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fname.setText("Full Name ");

        email.setText("Email ");

        address.setText("Address");

        phn.setText("Phone Number");

        jButton1.setText("SUBMIT ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Career Objective");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Academic Record");

        objective.setColumns(20);
        objective.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        objective.setRows(5);
        objective.setText("Want to be a part of an organization where i can fully utilize my skills and academic knowledge to make significantcontribution to the success of  organization and at the same time my individual growth.    ");
        jScrollPane2.setViewportView(objective);

        professional.setColumns(20);
        professional.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        professional.setRows(5);
        professional.setText("Professional Qualification :- Bachelor of engineering (second year-4th sem student ) from sushila devi bansal collegeof engineering,Indore(m.p.)in the stream of computer sience(2021-2022)(CGPA-9.00)");
        jScrollPane1.setViewportView(professional);

        educational.setColumns(20);
        educational.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        educational.setRows(5);
        educational.setText("Educational Qualification :- \n\t\t\t. Senior SEcondary School Certificate(10+2)from m.p. board with 75% in the year 2020\n\t\t\t. High Secondary School Certificate(10th) from m.p. board with 75% in the year 2018 ");
        jScrollPane3.setViewportView(educational);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Achievement ");

        achievement_1.setText("Achievement 1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Technical Skills");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Personal Information");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Self Declaration");

        achievement_2.setText("Achievement 2");

        achievement_3.setText("Achievement 3");

        skill_1.setText("C");

        skill_2.setText("JAVA");

        skill_3.setText("C++");

        dob.setText("DOB:");

        fathername.setText("Father's Name:");

        language.setText("Languages Known : Hindi and English");

        nationality.setText("Nationality:Indian");

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField11.setText("I hereby declare that the information mentioned here is true to the best of knowledge.");

        name.setText("Name:");

        date.setText("DATE:dd/mm/yy");

        place.setText("Place:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Key Strengths");

        strength_1.setText("Strength 1 ");

        strength_2.setText("Strength 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(phn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addComponent(address))
                            .addGap(986, 986, 986)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(achievement_3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(achievement_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                        .addComponent(achievement_2, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(skill_3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(skill_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(skill_1, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(strength_2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(strength_1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nationality, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(language, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dob, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fathername, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(place, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(phn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(achievement_1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(skill_1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dob)
                        .addComponent(jTextField11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(achievement_2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(skill_2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fathername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(achievement_3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(skill_3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(language, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(9, 9, 9)
                        .addComponent(strength_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(strength_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(place, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            
           
//          String query="INSERT INTO details(full_name, email, address, phn_num, objective, professional, educational, achievement_1, achievement_2,achievement_3, strength_1, strength_2, skill_1, skill_2, skill_3, dob,father_name, language, nationality, name, date, place) VALUES ("+fname+","+email+","+phn+","+objective+","+professional+","+educational+","+achievement_1+","+achievement_2+","+achievement_3+","+strength_1+","+strength_2+","+skill_1+","+skill_2+","+skill_3+","+dob+","+fathername+","+language+","+nationality+","+name+","+date+","+place+")";
//            String query="INSERT INTO information(fname, lname, enroll, email) VALUES (?,'?','?','?')";
//             con = DriverManager.getConnection("jdbc:mysql://localhost/test","root","");
//             pst = con.prepareStatement(query);
//             pst.setString(1, fname.getText());
//             pst.setString(2, email.getText());
//             pst.setString(3, address.getText());
//             pst.setString(4, phn.getText());
//             pst.setString(5, objective.getText());
//             pst.setString(6, professional.getText());
//             pst.setString(7, educational.getText());
//             pst.setString(8, achievement_1.getText());
//             pst.setString(9, achievement_2.getText());
//             pst.setString(10, achievement_3.getText());
//             pst.setString(11, strength_1.getText());
//             pst.setString(12, strength_2.getText());
//             pst.setString(13, skill_1.getText());
//             pst.setString(14, skill_2.getText());
//             pst.setString(15, skill_3.getText());
//             pst.setString(16, dob.getText());
//             pst.setString(17, fathername.getText());
//             pst.setString(18, language.getText());
//             pst.setString(19, nationality.getText());
//             pst.setString(20, name.getText());
//             pst.setString(21, date.getText());
//             pst.setString(22, place.getText());
               pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"REGISTERD SUCCESSFULLY");
            
            
            JFileChooser dialog = new JFileChooser();
            dialog.setSelectedFile(new File(fname.getText()+".pdf"));
            int dialogResult = dialog.showSaveDialog(null);
            if (dialogResult==JFileChooser.APPROVE_OPTION){
            String filePath = dialog.getSelectedFile().getPath();
            
                try {
                    Document myDocument = new Document();
                    PdfWriter myWriter = PdfWriter.getInstance(myDocument, new FileOutputStream(filePath));

                    myDocument.open();
                    PdfPTable table = new PdfPTable(3);
                    table.getDefaultCell().setBorder(0);
                    myDocument.add(new Paragraph(fname.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph(email.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph(address.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
                    myDocument.add(new Paragraph(phn.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD, BaseColor.DARK_GRAY)));
                   
                    myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
                    
//                    myDocument.add(new Paragraph("Career Objective",FontFactory.getFont(FontFactory.TIMES_BOLD,14,Font.BOLD,BaseColor.DARK_GRAY )));
//                    myDocument.add(new Paragraph(objective.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,12,Font.PLAIN,BaseColor.DARK_GRAY  )));
//         
//                    myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
//                   
//                    myDocument.add(new Paragraph("Academic Record", FontFactory.getFont(FontFactory.TIMES_BOLD, 14, Font.BOLD, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph(professional.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
//                    System.getProperty("line.separator");
//                    myDocument.add(new Paragraph(educational.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
//                   
//                    myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
//                    
//                    myDocument.add(new Paragraph("Achievements", FontFactory.getFont(FontFactory.TIMES_BOLD, 14, Font.BOLD, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph(achievement_1.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph(achievement_2.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph(achievement_3.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
//                  
//                    myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
//                   
//                    myDocument.add(new Paragraph("Key Strengths", FontFactory.getFont(FontFactory.TIMES_BOLD, 14, Font.BOLD, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph(strength_1.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph(strength_2.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
//                    
//                    myDocument.add(new Paragraph("SKILLS", FontFactory.getFont(FontFactory.TIMES_BOLD, 14, Font.BOLD, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph(skill_1.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph(skill_2.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph(skill_3.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
//                    
//                     
//                    myDocument.add(new Paragraph("Personal Information", FontFactory.getFont(FontFactory.TIMES_BOLD, 14, Font.BOLD, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph(dob.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph(fathername.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph(language.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph(nationality.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
//          
//                    myDocument.add(new Paragraph("Self Declaration", FontFactory.getFont(FontFactory.TIMES_BOLD, 14, Font.BOLD, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph(name.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph(date.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
//                    myDocument.add(new Paragraph(place.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.PLAIN, BaseColor.DARK_GRAY)));
//                    
                    
                    myDocument.close();
                } catch (Exception e) {

                }
            }

    }//GEN-LAST:event_jButton1ActionPerformed
catch (Exception e) {

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CREATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CREATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CREATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CREATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CREATE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField achievement_1;
    private javax.swing.JTextField achievement_2;
    private javax.swing.JTextField achievement_3;
    private javax.swing.JTextField address;
    private javax.swing.JTextField date;
    private javax.swing.JTextField dob;
    private javax.swing.JTextArea educational;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fathername;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField language;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nationality;
    private javax.swing.JTextArea objective;
    private javax.swing.JTextField phn;
    private javax.swing.JTextField place;
    private javax.swing.JTextArea professional;
    private javax.swing.JTextField skill_1;
    private javax.swing.JTextField skill_2;
    private javax.swing.JTextField skill_3;
    private javax.swing.JTextField strength_1;
    private javax.swing.JTextField strength_2;
    // End of variables declaration//GEN-END:variables
}
